# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur_manipulator_controller:
      type: joint_trajectory_controller/FollowJointTrajectory


    gripper_controller:
      type: gripper_controller/GripperCommand


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur_manipulator_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []
gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    command_interfaces:
      []
    state_interfaces:
      []